"""Generate HTML diffs using DaisyDiff by comparing HTML documentation
files generated by Doxygen and ConfiGen.
"""

import logging
import os
import shutil
import subprocess

import pandas as pd
import progressbar
import xlsxwriter
from lxml import html

from config import root_dir
from utils import create_dir
from utils import read_csv_to_df



def run_doxygen_doc_diff(project_config):
    generate_doxygen_autoconf_doc_diff_for_versions(project_config)
    copy_excels_to_data_dir(project_config)
    combine_excels(project_config)
    pass


def generate_doxygen_autoconf_doc_diff_for_versions(project_config):
    df = read_csv_to_df(project_config.file_commit_ids_versions)
    bar = progressbar.ProgressBar(max_value=len(df), redirect_stdout=True).start()
    for i, row in df.iterrows():
        doxygen_autoconf_doc_diff(project_config, row['sha'])
        bar.update(i + 1)
    bar.finish()


def doxygen_autoconf_doc_diff(project_config, commit_id):
    """Compare HTML files from documentations of a commit generated
    by Doxygen and ConfiGen, and generate HTML diffs using DaisyDiff.

    The directory structure is kept same as the documentation of a commit.
    To see the diff, open the index.html file in a browser same as the way
    you open the index.html file for a commit's documentation.
    Use the left side navigation panel and select a file. If there are changes
    between the two commits' documentation for this file, you will see those 
    changes in green or red colors. Otherwise, the file's documentation will
    look similar to a normal documentation file.

    Note: It is assumed that the DaisyDiff repository is cloned and kept
    in the same directory level as this project's repository - kconfig_doc.
    For example, if 'kconfig_doc' is cloned and kept under 'configen'
    directory, then 'DaisyDiff' should also be cloned and kept under
    'configen' directory. Otherwise, this function cannot not access the jar
    file properly.

    Parameters
    ----------
    project_config
        Project specific config options. i.e., variables from 
        config_bbox.py file for BusyBox.
    commit_id : str
        Commit id for which the documentation will be compared with.
    """
    logging.info('[{}] Generating Doxygen and ConfiGen diff for commit {}'
                 .format(project_config.project_name, commit_id[:7]))

    daisydiff_dir = os.path.join(os.path.dirname(root_dir), 'DaisyDiff')
    daisydiff_jar = os.path.join(daisydiff_dir, 'target',
                                 'daisydiff-1.2-jar-with-dependencies.jar')
    if daisydiff_jar == None:
        logging.error(('[{}][doxygen_autoconf_doc_diff] Could not find '
                       'DaisyDiff jar file. '
                      'Follow README to build the jar file.')
                      .format(project_config.project_name))
        return -1

    doxygen_doc_dir = os.path.join(project_config.project_doxygen_doc_dir,
                                   commit_id, 'html')
    autoconf_doc_dir = os.path.join(project_config.project_doc_dir,
                                    commit_id, 'html')

    # Check documentation exist or not.
    # Documentation 'html' dir might exist with only 'kconfig' dir containing
    # XML files. That means, doxygen only generated XML files and HTML files
    # are not generated. Check this by counting number of items in 'html' dir.
    # If does not exist the documentation, show error and exit.
    if not os.path.isdir(doxygen_doc_dir) or len(os.listdir(doxygen_doc_dir)) < 2:
        logging.error('[{}][doxygen_autoconf_doc_diff] Doxygen documentation does not exist for commit {}.'
                      .format(project_config.project_name, commit_id))
        return -1
    if not os.path.isdir(autoconf_doc_dir) or len(os.listdir(autoconf_doc_dir)) < 2:
        logging.error('[{}][doxygen_autoconf_doc_diff] ConfiGen documentation does not exist for commit {}.'
                      .format(project_config.project_name, commit_id))
        return -1

    diff_dir = os.path.join(project_config.project_doxy_auto_diff_dir,
                            commit_id[:7] + '_' + commit_id[:7], 'html')
    create_dir(diff_dir)
    copy_doxygen_files(autoconf_doc_dir, diff_dir)

    filenames = extract_filenames(project_config, commit_id)
    # filenames = {'loginutils/chpasswd.c': {'left': '/home/jobayer/workspace/kconfig_doc/commit_parser/data/temp/doxygen_doc/busybox/70f77e4617e06077231b8b63c3fb3406d7f8865d/html/dc/d8a/chpasswd_8c.html', 'right': '/home/jobayer/workspace/kconfig_doc/commit_parser/data/temp/autoconf_doc/busybox/70f77e4617e06077231b8b63c3fb3406d7f8865d/html/dc/d8a/chpasswd_8c.html'}}

    bar = progressbar.ProgressBar(max_value=len(filenames),
                                  redirect_stdout=True).start()
    added_files, deleted_files, changed_files = {}, {}, {}
    index = 0
    for filename, pair in filenames.items():
        if 'left' in pair:
            if 'right' in pair: # modified
                copy_daisydiff_files(daisydiff_dir, diff_dir,
                                     pair['right'])
                diff_file = generate_html_diff(project_config, pair['left'],
                                               pair['right'], diff_dir,
                                               filename, daisydiff_jar)
                change_obj = diff_changes(diff_file)
                if change_obj:
                    changed_files[filename] = {k: v for k, v in change_obj.items()}
            else: # deleted
                empty_file = os.path.join(project_config.project_doc_dir,
                                          commit_id, 'html', 'del',
                                          'a' + str(len(deleted_files)),
                                          os.path.basename(pair['left']))
                create_empty_html_file(empty_file)
                copy_daisydiff_files(daisydiff_dir, diff_dir, empty_file)
                diff_file = generate_html_diff(project_config, pair['left'],
                                               empty_file, diff_dir,
                                               filename, daisydiff_jar)
                change_obj = diff_changes(diff_file)
                if change_obj:
                    deleted_files[filename] = {k: v for k, v in change_obj.items()}
        else: # added
            empty_file = os.path.join(project_config.project_doxygen_doc_dir,
                                      commit_id, 'html', 'add',
                                      'a' + str(len(added_files)),
                                      os.path.basename(pair['right']))
            create_empty_html_file(empty_file)
            copy_daisydiff_files(daisydiff_dir, diff_dir, pair['right'])
            diff_file = generate_html_diff(project_config, empty_file, 
                                           pair['right'], diff_dir,
                                           filename, daisydiff_jar)
            change_obj = diff_changes(diff_file)
            if change_obj:
                added_files[filename] = {k: v for k, v in change_obj.items()}
        index += 1
        bar.update(index)
    bar.finish()

    # write data to excel
    added_files = {k: added_files[k] for k in sorted(added_files)}
    deleted_files = {k: deleted_files[k] for k in sorted(deleted_files)}
    changed_files = {k: changed_files[k] for k in sorted(changed_files)}

    excel_file = os.path.join(os.path.dirname(diff_dir),
                               'diff_changes.xlsx')
    diff_data = {'added_files': added_files,
                 'deleted_files': deleted_files,
                 'changed_files': changed_files}
    write_diff_changes(excel_file, diff_data)
    
    # remove empty html files from 'add' and 'del' directories
    add_dir = os.path.join(project_config.project_doxygen_doc_dir, commit_id,
                           'html', 'add')
    del_dir = os.path.join(project_config.project_doc_dir, commit_id, 'html',
                           'del')
    if os.path.exists(add_dir) and os.path.isdir(add_dir):
        shutil.rmtree(add_dir)
    if os.path.exists(del_dir) and os.path.isdir(del_dir):
        shutil.rmtree(del_dir)


def copy_doxygen_files(doc_dir, diff_dir):
    logging.info('Copying documentation files ...')
    shutil.copytree(doc_dir, diff_dir, dirs_exist_ok=True)


def copy_daisydiff_files(daisydiff_dir, commit_diff_dir, right_file):
    dir_path = os.path.dirname(right_file)
    path_components = dir_path.split('/')
    html_index = len(path_components) - path_components[::-1].index('html') - 1
    dirs_under_html = path_components[html_index + 1 : ]
    dest_dir = os.path.join(commit_diff_dir, '/'.join(dirs_under_html))

    shutil.copytree(os.path.join(daisydiff_dir, 'css'),
                    os.path.join(dest_dir, 'css'), dirs_exist_ok=True)
    shutil.copytree(os.path.join(daisydiff_dir, 'js'),
                    os.path.join(dest_dir, 'js'), dirs_exist_ok=True)
    shutil.copytree(os.path.join(daisydiff_dir, 'images'),
                    os.path.join(dest_dir, 'images'), dirs_exist_ok=True)
    

def extract_filenames(project_config, commit_id):
    """Read html doc file names and extract original file names.
    Store original file names and their corresponding html file names
    in a dictionary.
    """
    # logging.info('Extracting file names ...')

    # original_filename: {
    #     left: commit1 html file path,
    #     right: commit2 html file path
    # }
    data = {} 
    doxygen_doc_dir = os.path.join(project_config.project_doxygen_doc_dir,
                                   commit_id, 'html')
    dir_list = [os.path.join(doxygen_doc_dir, d) for d 
                in os.listdir(doxygen_doc_dir) 
                if os.path.isdir(os.path.join(doxygen_doc_dir, d))]
    for dir in dir_list:
        for root, dirs, files in os.walk(dir):
            for filename_o in files:
                if not filename_o.endswith(('_8c.html', '_8h.html')):
                    continue
                file_path_o = os.path.join(root, filename_o)
                filename = parse_filename(file_path_o)
                if filename is None:
                    logging.error('Failed to extract filename from {}'
                                  .format(file_path_o))
                    continue
                data[filename] = {'left': file_path_o}

    autoconf_doc_dir = os.path.join(project_config.project_doc_dir, commit_id,
                                    'html')
    dir_list = [os.path.join(autoconf_doc_dir, d) for d 
                in os.listdir(autoconf_doc_dir) 
                if os.path.isdir(os.path.join(autoconf_doc_dir, d))]
    for dir in dir_list:
        for root, dirs, files in os.walk(dir):
            for filename_o in files:
                if not filename_o.endswith(('_8c.html', '_8h.html')):
                    continue
                file_path_o = os.path.join(root, filename_o)
                filename = parse_filename(file_path_o)
                if filename is None:
                    logging.error('Failed to extract filename from {}'
                                  .format(file_path_o))
                    continue
                if filename in data:
                    data[filename]['right'] = file_path_o
                else:
                    data[filename] = {'right': file_path_o}
    return data


def parse_filename(html_file_path):
    """Read HTML file and extract original file path from the nav-path div."""
    if not html_file_path or not os.path.isfile(html_file_path):
        return None

    with open( html_file_path, 'rb') as f:
        lines = f.readlines()
    html_content = b''.join(lines).decode(encoding='utf-8', errors='ignore')
    tree = html.fromstring(html_content)

    nav_path_divs = tree.xpath('//div[@id="nav-path"]')
    if len(nav_path_divs) < 1:
        return None
    li_tags = nav_path_divs[0].xpath(f'.//ul/li[@class="navelem"]/a[@class="el"]')
    paths = [a.text.strip() for a in li_tags if a.text.strip() is not None]
    if len(paths) < 1:
        return None
    filename = os.path.join(*paths)
    return filename
                

def create_empty_html_file(empty_file):
    html_code = """
    <html>
        <head>
            <META http-equiv="Content-Type" content="text/html; charset=UTF-8">
        </head>
        <body>
            <div id="top">
                <div id="titlearea">
                    <table cellspacing="0" cellpadding="0">
                        <tbody>
                            <tr id="projectrow">
                                <td id="projectalign">
                                    <div id="projectname">BusyBox </div>
                                </td>
                            </tr>
                        </tbody>
                    </table>
                </div>
                <div id="main-nav"></div>
            </div>
            <div id="nav-path" class="navpath">
                <ul>
                    <li class="footer">
                        Generated by 
                        <a href="https://www.doxygen.org/index.html">
                            <img class="footer" src="../../doxygen.svg" width="104" height="31" alt="doxygen">
                        </a>
                        1.9.5
                    </li>
                </ul>
            </div>
        </body>
    </html>
    """
    create_dir(os.path.dirname(empty_file))
    with open(empty_file, 'w') as f:
        f.write(html_code)


def generate_html_diff(project_config, left_file, right_file, commit_diff_dir,
                       original_filename, daisydiff_jar):
    # logging.info('Comparing file {} ...'.format(original_filename))
    path_components = right_file.split('/')
    path_components.reverse()
    html_index = path_components.index('html')
    parent_path = '/'.join(['..'] * (html_index - 1))
    commit_id = path_components[html_index + 1]

    paths_under_html = path_components[ : html_index]
    paths_under_html.reverse()
    output_file = os.path.join(commit_diff_dir, '/'.join(paths_under_html))

    css_files = ['tabs.css', 'navtree.css', 'search/search.css', 'doxygen.css']
    css_files = [os.path.join(parent_path, item) for item in css_files]
    css_files = ';'.join(css_files)

    js_files = ['jquery.js', 'dynsections.js', 'resize.js', 'navtreedata.js',
                'navtree.js', 'search/searchdata.js', 'search/search.js']
    js_files = [os.path.join(parent_path, item) for item in js_files]
    js_files = ';'.join(js_files)
    
    command = ['java', '-jar', f'{daisydiff_jar}', f'{left_file}',
                f'{right_file}', f'--file={output_file}',
                f'--css={css_files}', f'--js={js_files}',
                '--doxygen', '--q']
    
    try:
        r = subprocess.run(command, timeout=60*5)
        if r.returncode != 0:
            logging.error(('[{}][html_diff] Failed to generate HTML diff for '
                           'file {} in commit {}')
                           .format(project_config.project_name,
                                   original_filename, commit_id[:7]))
            return None
    except subprocess.TimeoutExpired:
        logging.error(('[{}][html_diff] Timeout to generate HTML diff for '
                        'file {} in commit {}')
                        .format(project_config.project_name,
                                original_filename, commit_id[:7]))
        return None
    return output_file


def diff_changes(diff_file):
    """Read the HTML diff file generated by DaisyDiff, find element with 
    id='first-diff' and check diff has changes or not.
    Also, check changes are only in Kconfig parts, only in non-Kconfig parts
    or both by parsing 'data-kconfig' attributes.
    """
    if not diff_file or not os.path.isfile(diff_file):
        return None
    
    with open( diff_file, 'rb') as f:
        lines = f.readlines()
    html_content = b''.join(lines).decode(encoding='utf-8', errors='ignore')
    tree = html.fromstring(html_content)
    
    data = {'config': 0, 'defined_at': 0, 'used_at': 0, 'non_config': ''}

    # Check any changes exist in the diff file.
    # Parse div with class='diff-topbar'.
    # If there is any change, this div will contain
    # an a tag with id='first-diff'.
    diff_topbar = tree.xpath('//div[@class="diff-topbar"]')
    if len(diff_topbar) < 1:
        return data
    first_diff = diff_topbar[0].xpath('.//a[@id="first-diff"]')
    if len(first_diff) < 1:
        return data
    href_value = first_diff[0].get('href')
    if href_value == '#':
        return data

    changed_definition_count = 0
    changed_define_count = 0
    changed_use_count = 0
    total_config_diff_span = 0

    # Kconfig header summary: 3
    # Kconfigs: 1
    # Each kdef summary: 3
    # Kconfig Documentation title: 1
    extra_html_diff = 3 + 1
    kdef_items = 0

    # Check changes in Kconfig symbol summary part.
    config_summary_table = tree.xpath('//a[@id="kconfig-members"]/ancestor::table[@class="memberdecls"]')
    if len(config_summary_table) > 0:
        diff_html = config_summary_table[0].xpath('.//span[contains(@class, "diff-html-")]')
        total_config_diff_span += len(diff_html)
        # For each newly declared kdef, there are 3 diff-html- in each kdef description.
        # 2 * (diff_html-1)/3
        kdef_items = len(diff_html) - 1
        extra_html_diff += 2 * kdef_items // 3
        extra_html_diff += kdef_items * 3

    # Check changes in Kconfig symbol definition parts.
    config_divs = tree.xpath('//span[@data-kconfig="definition"]/ancestor::div[@class="memdoc"]')
    for div in config_divs:
        definition = div.xpath('.//span[@data-kconfig="definition"]')
        help = div.xpath('.//pre[@data-kconfig="help"]')
        defined_at = div.xpath('.//span[@data-kconfig="defined-at"]')
        used_at = div.xpath('.//span[@data-kconfig="used-at"]')

        def_diff_html, help_diff_html = [], []
        if len(definition) > 0:
            def_diff_html = definition[0].xpath('.//span[contains(@class, "diff-html-")]')
            total_config_diff_span += len(def_diff_html)
        if len(help) > 0:
            help_diff_html = help[0].xpath('.//span[contains(@class, "diff-html-")]')
            total_config_diff_span += len(help_diff_html)
        if len(def_diff_html) > 0 or len(help_diff_html) > 0:
            changed_definition_count += 1

        if len(defined_at) > 0:
            diff_html = defined_at[0].xpath('.//span[contains(@class, "diff-html-")]')
            if len(diff_html) > 0:
                changed_define_count += 1
                total_config_diff_span += len(diff_html)

        if len(used_at) > 0:
            diff_html = used_at[0].xpath('.//span[contains(@class, "diff-html-")]')
            if len(diff_html) > 0:
                changed_use_count += 1
                total_config_diff_span += len(diff_html)

    data['config'] = changed_definition_count
    data['defined_at'] = changed_define_count
    data['used_at'] = changed_use_count

    total_diff_span = tree.xpath('//span[contains(@class, "diff-html-")]')
    if len(total_diff_span) > (total_config_diff_span + extra_html_diff):
        data['non_config'] = 'yes'

    return data


def write_diff_changes(excel_file, diff_data):
    wb = xlsxwriter.Workbook(excel_file)
    ws = wb.add_worksheet()

    filename                = ('filename', 0)
    config_change           = ('config change', 1)
    non_config_change       = ('non-config change', 2)
    changed_symbol_count    = ('config changed symbol count', 3)

    row = 0
    ws.write(row, filename[1], filename[0])
    ws.write(row, config_change[1], config_change[0])
    ws.write(row, non_config_change[1], non_config_change[0])
    ws.write(row, changed_symbol_count[1], changed_symbol_count[0])
    row += 1

    config_yes_count, non_config_yes_count, total_symbol_count = 0, 0, 0
    
    for file in diff_data['added_files']:
        ws.write(row, filename[1], file)
        symbol_count = diff_data['added_files'][file]['config']
        if symbol_count > 0:
            ws.write(row, config_change[1], 'yes')
            ws.write(row, changed_symbol_count[1], symbol_count)
            config_yes_count += 1
            total_symbol_count += symbol_count
        if diff_data['added_files'][file]['non_config']:
            ws.write(row, non_config_change[1],
                     diff_data['added_files'][file]['non_config'])
            non_config_yes_count += 1
        row += 1
    for file in diff_data['deleted_files']:
        ws.write(row, filename[1], file)
        symbol_count = diff_data['deleted_files'][file]['config']
        if symbol_count > 0:
            ws.write(row, config_change[1], 'yes')
            ws.write(row, changed_symbol_count[1], symbol_count)
            config_yes_count += 1
            total_symbol_count += symbol_count
        if diff_data['deleted_files'][file]['non_config']:
            ws.write(row, non_config_change[1],
                     diff_data['deleted_files'][file]['non_config'])
            non_config_yes_count += 1
        row += 1
    for file in diff_data['changed_files']:
        ws.write(row, filename[1], file)
        symbol_count = diff_data['changed_files'][file]['config']
        if symbol_count > 0:
            ws.write(row, config_change[1], 'yes')
            ws.write(row, changed_symbol_count[1], symbol_count)
            config_yes_count += 1
            total_symbol_count += symbol_count
        if diff_data['changed_files'][file]['non_config']:
            ws.write(row, non_config_change[1],
                     diff_data['changed_files'][file]['non_config'])
            non_config_yes_count += 1
        row += 1

    num_rows = ws.dim_rowmax + 1

    # total file
    total = (len(diff_data['added_files']) + len(diff_data['deleted_files'])
             + len(diff_data['changed_files']))
    ws.write(num_rows, filename[1], total)

    # total config change yes count
    ws.write(num_rows, config_change[1], config_yes_count)

    # total non config change
    ws.write(num_rows, non_config_change[1], non_config_yes_count)

    # total config symbol change count
    ws.write(num_rows, changed_symbol_count[1], total_symbol_count)

    ws.freeze_panes(1, 0)
    wb.close()


def copy_excels_to_data_dir(project_config):
    df = read_csv_to_df(project_config.file_commit_ids_versions)
    for _, row in df.iterrows():
        commit_id = row['sha']
        src_file = os.path.join(project_config.project_doxy_auto_diff_dir,
                                commit_id[:7] + '_' + commit_id[:7],
                                'diff_changes.xlsx')
        dst_dir = os.path.join(project_config.project_doxy_diff_data_html_dir,
                                commit_id[:7] + '_' + commit_id[:7])
        dst_file = os.path.join(dst_dir,'diff_changes.xlsx')
        if os.path.isfile(src_file):
            if not os.path.exists(dst_dir):
                os.makedirs(dst_dir)
            shutil.copy(src_file, dst_file)
        else:
            logging.error('[{}] Could not copy Doxygen diff_changes.xlsx file for {}'
                          .format(project_config.project_name, commit_id))


def combine_excels(project_config):
    logging.info('[{}] Combining Doxygen diff_changes.xlsx files for versions'
                 .format(project_config.project_name))
    version_df = read_csv_to_df(project_config.file_commit_ids_versions)

    data = []
    headings = ['Version',
                'Year',
                'Total source code files',
                # Files that have changes because of Kconfig inclusion
                'Total ConfiGen files with Kconfig info',
                # Files that have changes because of source code.
                # It should be 0 and is 0. So, removed.
                # 'Total ConfiGen changed files for source code',
                'Total Kconfig symbol definitions found in ConfiGen files']
    data.append(headings)
    combined_excel = os.path.join(project_config.project_doxy_diff_data_html_dir,
                                  'diff_changes.xlsx')
    with pd.ExcelWriter(combined_excel, engine='xlsxwriter') as writer:
        for _, row in version_df.iterrows():
            tag = row['tag']
            year = row['year']
            commit_id = row['sha']
            excel_file = os.path.join(project_config.project_doxy_diff_data_html_dir,
                                      commit_id[:7] + '_' + commit_id[:7],
                                      'diff_changes.xlsx')
            if os.path.exists(excel_file) and os.path.isfile(excel_file):
                df = pd.read_excel(excel_file)
                df.to_excel(writer, sheet_name=tag, index=False)
                worksheet = writer.sheets[tag]
                worksheet.freeze_panes(1, 0)
                
                last_row_values = df.iloc[-1].values
                sum_row = [tag,
                           year,
                           last_row_values[0],
                           last_row_values[1],
                           last_row_values[3]]
                data.append(sum_row)
            else:
                logging.error('[{}] Doxygen diff file diff_changes.xlsx does not exist for {}'
                              .format(project_config.project_name, commit_id[:7]))

    summary_excel = os.path.join(project_config.project_doxy_diff_data_html_dir,
                                 'diff_changes_summary.xlsx')
    wb = xlsxwriter.Workbook(summary_excel)
    ws = wb.add_worksheet()
    ws.set_column('A:E', 20)

    # Convert the 5th column to int, except the first row.
    for i in range(1, len(data)):
        for j in range(len(data[0])):
            if j == 4:
                data[i][j] = int(data[i][j])

    for i, row in enumerate(data):
        for j, value in enumerate(row):
            ws.write(i, j, str(value))

    ws.freeze_panes(1, 0)
    wb.close()

    # Save to csv
    summary_df = pd.read_excel(summary_excel)
    summary_df = summary_df.iloc[::-1].reset_index(drop=True)
    summary_df['Version'] = summary_df['Version'].str.split('~').str[0]
    summary_df.to_csv(project_config.file_doxy_diff_changes_summary, header=True, index=False)
