"""Generate XML diffs by comparing two XML files containing Kconfig
symbol definitions. Diff file is an HTML table and the comparison is 
done by SequenceMatcher of difflib Python Standard Library.
"""

import ast
import logging
import copy
import os

from git import Repo
from lxml import etree
import xml.etree.ElementTree as ET
from difflib import SequenceMatcher
import pandas as pd

from utils import read_csv_to_df



def run_xml_diff(project_config):
    generate_xml_diffs(project_config)
    
    # xml_diff(project_config, 'd784b65be71f8ddae433ab9bee4e2ad953097716', '0d8ea64af618dc83c3291b3b598636ed3d0854e4')
    pass


def generate_xml_diffs(project_config):
    """Generate XML diffs for random commits."""
    logging.info('[{}] Generating XML diffs for random commits...'
                 .format(project_config.project_name))

    # 
    # BusyBox
    # 
    # '01986e9c6f45e718a11c8cd7a37306b54b78b501'
    # '90801dadfa06e2277d136132f71a75569593eda4'
    # FEATURE_FIND_NOT usage exists because the deleted one was duplicate of 
    # FEATURE_FIND_NOT. That's why usage exists.
    # FEATURE_VOLUMEID_SQUASHFS usage exists because the deleted one was 
    # duplicate in util-linux/volume_id/squashfs.c. This already declared in 
    # util-linux/Config.src in the same parent commit.

    # check_kdef_del_usage_exist(config_bbox)
    # check_kdef_del_usage_exist(config_toybox) # not found
    # check_kdef_del_usage_exist(config_uclibc) # not found

    random_df = read_csv_to_df(project_config.file_commit_ids_random_kdef)
    repo = Repo(project_config.project_repo_dir)

    for index, row in random_df.iterrows():
        parent_id = repo.commit(row['sha']).parents[0].hexsha
        xml_diff(project_config, parent_id, row['sha'])


def xml_diff(project_config, commit_id1, commit_id2):
    """Compare XML file of two commits and show the diff in an HTML table.
    
    AutoConfDoc generates two XML files for a commit - one with Kconfig symbol 
    definitions and other with the usage of Kconfig symbols as #ifdef macro
    in source code. This function compares two definition XML files
    and shows the changes in an HTML table.
    The same goes for the usage XML file.

    The final output is an HTML file containing two tables - one is for symbol
    definitions and another one is for macro usage.

    Note: before using this function, make sure that the XML files of the 
    commits and their parent commits are generated by AutoConfDoc
    and kept in the corresponding project XML directory 
    (see variable project_xml_dir in config_*.py file).
    """
    logging.info('[{}] Generating XML diff between commit {} and {}'.format(
        project_config.project_name, commit_id1[:7], commit_id2[:7]))

    config_table = create_config_table(project_config, commit_id1, commit_id2)
    # usage_table = create_usage_table(project_config, commit_id1, commit_id2)

    if config_table is None:
        logging.error('[{}][xml_diff] Failed to generate XML diff between {} and {}'
                      .format(project_config.project_name, commit_id1[:7], commit_id2[:7]))
        return

    html = get_html(commit_id1, commit_id2, config_table)
    output_file = os.path.join(project_config.project_xml_diff_dir,
                               commit_id1[:7] + '_' + commit_id2[:7]
                               + '_xml_diff.html')
    with open(output_file, 'w') as f:
        f.write(html)


def create_config_table(project_config, commit_id1, commit_id2):
    left_config_xml = os.path.join(project_config.project_xml_dir,
                                   commit_id1 + '_defs.xml')
    right_config_xml = os.path.join(project_config.project_xml_dir,
                                    commit_id2 + '_defs.xml')

    if not os.path.isfile(left_config_xml):
        logging.error('[{}][xml_diff] defs.xml file not found for commit {}'
                      .format(project_config.project_name, commit_id1[:7]))
        return None
    if not os.path.isfile(right_config_xml):
        logging.error('[{}][xml_diff] defs.xml file not found for commit {}'
                      .format(project_config.project_name, commit_id2[:7]))
        return None

    data = get_kdef_data(left_config_xml, right_config_xml)
    df = pd.DataFrame.from_dict(data, orient='index')

    colored_df = color_kdef(df)
    if not colored_df.empty:
        colored_df['parent_kdef'] = colored_df['parent_kdef'].apply(
            lambda x: x['info'] if x else '')
        colored_df['commit_kdef'] = colored_df['commit_kdef'].apply(
            lambda x: x['info'] if x else '')
        colored_df['parent_kdef'] = colored_df['parent_kdef'].apply(
            lambda x: x.replace('\n', '<br>')
            .replace('\t', '&nbsp;&nbsp;&nbsp;&nbsp;') if x else '')
        colored_df['commit_kdef'] = colored_df['commit_kdef'].apply(
            lambda x: x.replace('\n', '<br>')
            .replace('\t', '&nbsp;&nbsp;&nbsp;&nbsp;') if x else '')
        colored_df = colored_df.reset_index()
        colored_df.columns = ['Kconfig', 'Commit ' + commit_id1[:7],
                              'Commit ' + commit_id2[:7]]
    table = colored_df.to_html(None, escape=False, bold_rows=False, 
                               index=False)
    return table


def get_kdef_data(left_kdef_xml, right_kdef_xml):
    # {filename: {kdef_name: kdef_info}}
    left_kdefs = parse_kdef_xml(left_kdef_xml)
    right_kdefs = parse_kdef_xml(right_kdef_xml)

    common_filenames = list(set(left_kdefs.keys()) & set(right_kdefs.keys()))
    left_filenames = list(set(left_kdefs.keys()) - set(right_kdefs.keys()))
    right_filenames = list(set(right_kdefs.keys()) - set(left_kdefs.keys()))
    common_filenames.sort()
    left_filenames.sort()
    right_filenames.sort()

    # {kdef_name: (kdef, kdef)}
    result = {}
    # {kdef_name: kdef}
    all_left_kdefs = {}
    all_right_kdefs = {}
    for filename in common_filenames:
        common_kdef_names = list(set(left_kdefs[filename].keys()) 
                                 & set(right_kdefs[filename].keys()))
        left_kdef_names = list(set(left_kdefs[filename].keys()) 
                               - set(right_kdefs[filename].keys()))
        right_kdef_names = list(set(right_kdefs[filename].keys()) 
                                - set(left_kdefs[filename].keys()))
        common_kdef_names.sort()
        left_kdef_names.sort()
        right_kdef_names.sort()

        for item in common_kdef_names:
            left_kdef = left_kdefs[filename][item]
            right_kdef = right_kdefs[filename][item]
            if item in all_left_kdefs:
                logging.error('Duplicate Kconfig in parent: {}'.format(item))
            else:
                all_left_kdefs[item] = left_kdef
            if item in all_right_kdefs:
                logging.error('Duplicate Kconfig in commit: {}'.format(item))
            else:
                all_right_kdefs[item] = right_kdef

        for item in left_kdef_names:
            left_kdef = left_kdefs[filename][item]
            if item in all_left_kdefs:
                logging.error('Duplicate Kconfig in parent: {}'.format(item))
            else:
                all_left_kdefs[item] = left_kdef

        for item in right_kdef_names:
            right_kdef = right_kdefs[filename][item]
            if item in all_right_kdefs:
                logging.error('Duplicate Kconfig in commit: {}'.format(item))
            else:
                all_right_kdefs[item] = right_kdef

    for filename in left_filenames:
        for item in left_kdefs[filename].keys():
            left_kdef = left_kdefs[filename][item]
            if item in all_left_kdefs:
                logging.error('Duplicate Kconfig in parent: {}'.format(item))
            else:
                all_left_kdefs[item] = left_kdef

    for filename in right_filenames:
        for item in right_kdefs[filename].keys():
            right_kdef = right_kdefs[filename][item]
            if item in all_right_kdefs:
                logging.error('Duplicate Kconfig in commit: {}'.format(item))
            else:
                all_right_kdefs[item] = right_kdef

    common_kdef_names = list(set(all_left_kdefs.keys()) 
                                 & set(all_right_kdefs.keys()))
    left_kdef_names = list(set(all_left_kdefs.keys()) 
                            - set(all_right_kdefs.keys()))
    right_kdef_names = list(set(all_right_kdefs.keys()) 
                            - set(all_left_kdefs.keys()))
    
    common_kdef_names.sort()
    left_kdef_names.sort()
    right_kdef_names.sort()

    for item in common_kdef_names:
        left_kdef = all_left_kdefs[item]
        right_kdef = all_right_kdefs[item]
        if left_kdef['info'] != right_kdef['info']:
            if item in result:
                logging.error('Kconfig already exist in result {}'.format(item))
            else:
                result[item] = (left_kdef, right_kdef)

    for item in left_kdef_names:
        left_kdef = all_left_kdefs[item]
        if item in result:
            logging.error('Left Kconfig already exist in result {}'.format(item))
        else:
            result[item] = (left_kdef, None)

    for item in right_kdef_names:
        right_kdef = all_right_kdefs[item]
        if item in result:
            logging.error('Right Kconfig already exist in result {}'.format(item))
        else:
            result[item] = (None, right_kdef)

    # reshape the data to a flat dictionary
    flat_data = {}
    for k, v in result.items():
        flat_data[k] = {'parent_kdef': v[0], 
                            'commit_kdef': v[1]}

    sorted_data = {k: flat_data[k] for k in sorted(flat_data)}
    return sorted_data


def color_kdef(df):
    for _, row in df.iterrows():
        if row['parent_kdef'] is None: # add
            row['commit_kdef']['info'] = ('<span data-kconfig="add">' 
                                          + add_class('insert',
                                                      row['commit_kdef']['info'])
                                          + '</span>')
        elif row['commit_kdef'] is None: # delete
            row['parent_kdef']['info'] = ('<span data-kconfig="remove">' 
                                          + add_class('delete',
                                                      row['parent_kdef']['info'])
                                          + '</span>')
        else: # edit
            left_kdef = row['parent_kdef']
            right_kdef = row['commit_kdef']
            text_formats_3rd = ['config ' + left_kdef['name']]
            text_formats_4th = ['config ' + right_kdef['name']]

            left_str = left_kdef['type']
            if left_kdef['prompt']:
                left_str += ' ' + left_kdef['prompt']
            right_str = right_kdef['type']
            if right_kdef['prompt']:
                right_str += ' ' + right_kdef['prompt']
            left_parts, right_parts = get_colored_parts(left_str, right_str, 
                                                        '')
            text_formats_3rd.extend(left_parts)
            text_formats_4th.extend(right_parts)

            attr = 'defaults'
            attr_name = 'default'
            min_items = min(len(left_kdef[attr]), len(right_kdef[attr]))
            for i in range(min_items):
                left_parts, right_parts = get_colored_parts(left_kdef[attr][i],
                                                            right_kdef[attr][i],
                                                            attr_name)
                text_formats_3rd.extend(left_parts)
                text_formats_4th.extend(right_parts)
            for i in range(min_items, len(left_kdef[attr])):
                left_parts, right_parts = get_colored_parts(left_kdef[attr][i],
                                                            '', attr_name)
                text_formats_3rd.extend(left_parts)
                text_formats_4th.extend(right_parts)
            for i in range(min_items, len(right_kdef[attr])):
                left_parts, right_parts = get_colored_parts('',
                                                            right_kdef[attr][i],
                                                            attr_name)
                text_formats_3rd.extend(left_parts)
                text_formats_4th.extend(right_parts)

            attr = 'depends'
            attr_name = 'depends on'
            left_parts, right_parts = get_colored_parts(left_kdef[attr],
                                                        right_kdef[attr],
                                                        attr_name)
            text_formats_3rd.extend(left_parts)
            text_formats_4th.extend(right_parts)

            attr = 'selects'
            attr_name = 'select'
            min_items = min(len(left_kdef[attr]), len(right_kdef[attr]))
            for i in range(min_items):
                left_parts, right_parts = get_colored_parts(left_kdef[attr][i],
                                                            right_kdef[attr][i],
                                                            attr_name)
                text_formats_3rd.extend(left_parts)
                text_formats_4th.extend(right_parts)
            for i in range(min_items, len(left_kdef[attr])):
                left_parts, right_parts = get_colored_parts(left_kdef[attr][i],
                                                            '', attr_name)
                text_formats_3rd.extend(left_parts)
                text_formats_4th.extend(right_parts)
            for i in range(min_items, len(right_kdef[attr])):
                left_parts, right_parts = get_colored_parts('',
                                                            right_kdef[attr][i],
                                                            attr_name)
                text_formats_3rd.extend(left_parts)
                text_formats_4th.extend(right_parts)

            attr = 'implies'
            attr_name = 'imply'
            min_items = min(len(left_kdef[attr]), len(right_kdef[attr]))
            for i in range(min_items):
                left_parts, right_parts = get_colored_parts(left_kdef[attr][i],
                                                            right_kdef[attr][i],
                                                            attr_name)
                text_formats_3rd.extend(left_parts)
                text_formats_4th.extend(right_parts)
            for i in range(min_items, len(left_kdef[attr])):
                left_parts, right_parts = get_colored_parts(left_kdef[attr][i],
                                                            '', attr_name)
                text_formats_3rd.extend(left_parts)
                text_formats_4th.extend(right_parts)
            for i in range(min_items, len(right_kdef[attr])):
                left_parts, right_parts = get_colored_parts('',
                                                            right_kdef[attr][i],
                                                            attr_name)
                text_formats_3rd.extend(left_parts)
                text_formats_4th.extend(right_parts)

            attr = 'ranges'
            attr_name = 'range'
            min_items = min(len(left_kdef[attr]), len(right_kdef[attr]))
            for i in range(min_items):
                left_parts, right_parts = get_colored_parts(left_kdef[attr][i],
                                                            right_kdef[attr][i],
                                                            attr_name)
                text_formats_3rd.extend(left_parts)
                text_formats_4th.extend(right_parts)
            for i in range(min_items, len(left_kdef[attr])):
                left_parts, right_parts = get_colored_parts(left_kdef[attr][i],
                                                            '', attr_name)
                text_formats_3rd.extend(left_parts)
                text_formats_4th.extend(right_parts)
            for i in range(min_items, len(right_kdef[attr])):
                left_parts, right_parts = get_colored_parts('',
                                                            right_kdef[attr][i],
                                                            attr_name)
                text_formats_3rd.extend(left_parts)
                text_formats_4th.extend(right_parts)

            attr = 'help'
            attr_name = 'help'
            left_parts, right_parts = get_colored_parts(left_kdef[attr],
                                                        right_kdef[attr],
                                                        attr_name)
            text_formats_3rd.extend(left_parts)
            text_formats_4th.extend(right_parts)
            info_str = ''.join(text_formats_3rd)
            row['parent_kdef']['info'] = ('<span data-kconfig="modify">' 
                                          + info_str + '</span>')
            info_str = ''.join(text_formats_4th)
            row['commit_kdef']['info'] = ('<span data-kconfig="modify">' 
                                          + info_str + '</span>')
    return df


def get_colored_parts(left_str, right_str, attr_name):
    left_parts, right_parts = [], []

    attr_str = '\n\t' + attr_name
    if attr_name:
        attr_str += ' '

    if left_str == right_str:
        if len(left_str) == 0:
            return ([],[])
        left_parts.append(attr_str + left_str)
        right_parts.append(attr_str + right_str)
        return (left_parts, right_parts)
        
    if left_str:
        left_parts.append(attr_str)
    if right_str:
        right_parts.append(attr_str)

    s = SequenceMatcher(lambda x: x in " \t", left_str, right_str)
    for tag, i1, i2, j1, j2 in s.get_opcodes():
        if tag == 'equal':
            left_parts.append(left_str[i1:i2])
            right_parts.append(right_str[j1:j2])
        elif tag == 'insert':
            s = add_class(tag, right_str[j1:j2])
            right_parts.append(s)
        elif tag == 'delete':
            s = add_class(tag, left_str[i1:i2])
            left_parts.append(s)
        elif tag == 'replace':
            s = add_class('delete', left_str[i1:i2])
            left_parts.append(s)
            s = add_class('insert', right_str[j1:j2])
            right_parts.append(s)
    return (left_parts, right_parts)


def add_class(class_name: str, text: str):
    s = '<span class="{}">{}</span>'.format(class_name, text)
    return s


def get_html(commit_id1, commit_id2, kdef_table='', usage_table=''):
    html = f'''
    <!DOCTYPE html>
    <html>
    <head>
        <title>Kconfig Changes</title>
        <style>
            .heading {{
                width: 100%;
                text-align: center;
                font-weight: bold;
            }}
            .table-container {{
                overflow-x: auto;
            }}
            table {{
                border-collapse: collapse;
                width: 100%;
            }}
            table, td, th {{
                border: 1px solid lightgray;
            }}
            th, td {{
                text-align: left;
                padding: 8px;
            }}
            .insert {{
                background-color: #aaffaa;
            }}
            .delete {{
                background-color: #ffaaaa;
                text-decoration: line-through;
            }}
            .replace {{
                background-color: #ffff77;
            }}
        </style>
    </head>
    <body style="margin: 16px;">
    <div class="heading">{commit_id1[:7]} ~ {commit_id2[:7]}</div>
    <h3>Kconfig Definition Changes</h3>
    <div class="table-container">
    {kdef_table}
    </div>
    </body>
    </html>
    '''
    # <h3>Kconfig Usage Changes</h3>
    # <div class="table-container">
    # {usage_table}
    # </div>
    return html
        

def parse_kdef_xml(xml_file: str):
    parser = etree.XMLParser(encoding='ascii', recover=True)
    tree = etree.parse(xml_file, parser=parser)
    node_KconfigRoot = tree.getroot()
    # {filename: {kdef_name: kdef_info}}
    # kdef_info = {
    #   name: str,
    #   type: str,
    #   prompt: str,
    #   defaults: list(str),
    #   depends: str,
    #   selects: list(str),
    #   implies: list(str),
    #   ranges: list(str),
    #   help: str
    #   lineno: int,
    #   info: str
    # }
    data = {}
    for node_file in node_KconfigRoot:
        filename = node_file.attrib['fileName']
        for node_Kconfig in node_file:
            kdef = {
                'name': '',
                'type': '',
                'prompt': '',
                'defaults': [],
                'depends': '',
                'selects': [],
                'implies': [],
                'ranges': [],
                'help': '',
                'lineno': -1,
                'info': ''
            }
            info = 'config '
            name = node_Kconfig.attrib['name']
            kdef['name'] = name
            info += name
            type = node_Kconfig.find('type')
            kdef['type'] = type.text
            info += '\n\t' + type.text
            prompt = node_Kconfig.find('prompt')
            if prompt is not None:
                text = prompt.text
                item_depends = prompt.attrib['depends']
                if item_depends:
                    text += ' if ' + item_depends
                kdef['prompt'] = text
                info += ' ' + text
            defaults = node_Kconfig.findall('default')
            if defaults is not None:
                for item in defaults:
                    text = item.text
                    item_depends = item.attrib['depends']
                    if item_depends:
                        text += ' if ' + item_depends
                    kdef['defaults'].append(text)
                    info += '\n\tdefault ' + text
            depends = node_Kconfig.find('depends')
            if depends is not None:
                kdef['depends'] = depends.text
                info += '\n\tdepends on ' + depends.text
            selects = node_Kconfig.findall('select')
            if selects is not None:
                for item in selects:
                    text = item.text
                    item_depends = item.attrib['depends']
                    if item_depends:
                        text += ' if ' + item_depends
                    kdef['selects'].append(text)
                    info += '\n\tselect ' + text
            implies = node_Kconfig.findall('imply')
            if implies is not None:
                for item in implies:
                    text = item.text
                    item_depends = item.attrib['depends']
                    if item_depends:
                        text += ' if ' + item_depends
                    kdef['implies'].append(text)
                    info += '\n\timply ' + text
            ranges = node_Kconfig.findall('range')
            if ranges is not None:
                for item in ranges:
                    text = item.text
                    item_depends = item.attrib['depends']
                    if item_depends:
                        text += ' if ' + item_depends
                    kdef['ranges'].append(text)
                    info += '\n\trange ' + text
            help = node_Kconfig.find('help')
            if help is not None:
                help_text = '\n\t\t' + help.text.replace('\n', '\n\t\t')
                kdef['help'] = help_text
                info += '\n\thelp' + help_text
            lineno = node_Kconfig.find('lineno')
            if lineno is not None:
                kdef['lineno'] = lineno
            kdef['info'] = info
            if filename in data:
                data[filename][name] = copy.deepcopy(kdef)
            else:
                data[filename] = {name: copy.deepcopy(kdef)}
    return data



def check_kdef_del_usage_exist(project_config):
    """This function is to check whether any macro usage exist in source code 
    for a deleted Kconfig symbol definition.
    """
    kdef_df = read_csv_to_df(project_config.file_kdef)
    kdef_df['commit.committer.date'] = pd.to_datetime(
        kdef_df['commit.committer.date'])
    kdef_df = kdef_df.sort_values('commit.committer.date', ascending=True)
    kdef_df = kdef_df.reset_index(drop=True)
    kdef_df['files'] = kdef_df['files'].apply(ast.literal_eval)
    kdef_df['defs_move'] = kdef_df['defs_move'].apply(ast.literal_eval)

    doc_gen_df = read_csv_to_df(project_config.file_commit_ids_doc_gen_status)
    doc_gen_df['commit.committer.date'] = pd.to_datetime(
        doc_gen_df['commit.committer.date'])
    doc_gen_df = doc_gen_df.sort_values(
        'commit.committer.date', ascending=True)
    doc_gen_df = doc_gen_df.reset_index(drop=True)

    commit_ids_del = []
    for _, row in kdef_df.iterrows():
        doc_gen_rows = doc_gen_df.loc[doc_gen_df['sha'] == row['sha']]
        if doc_gen_rows.empty:
            continue
        if doc_gen_rows.iloc[0]['doc_gen_status'] == 'fail':
            continue
        usage_csv = os.path.join(
            project_config.project_xml_dir, row['sha'] + '_usage.csv')
        usage_df = read_csv_to_df(usage_csv)
        usage_df['files'] = usage_df['files'].apply(ast.literal_eval)
        for file in row['files']:
            only_del = file['only_del']
            is_exist = False
            for item in only_del:
                is_exist = (usage_df['kdef'] == item).any()
                if is_exist:
                    commit_ids_del.append(row['sha'])
                    break
            if is_exist:
                break
    logging.info('commit_ids_for_kdef_del_usage_exist for {}\n{}'
                 .format(project_config.project_name,
                         '\n'.join(commit_ids_del)))


def get_kdef_data_old(left_kdef_xml, right_kdef_xml):
    # {filename: {kdef_name: kdef_info}}
    left_kdefs = parse_kdef_xml(left_kdef_xml)
    right_kdefs = parse_kdef_xml(right_kdef_xml)

    common_filenames = list(set(left_kdefs.keys()) & set(right_kdefs.keys()))
    left_filenames = list(set(left_kdefs.keys()) - set(right_kdefs.keys()))
    right_filenames = list(set(right_kdefs.keys()) - set(left_kdefs.keys()))
    common_filenames.sort()
    left_filenames.sort()
    right_filenames.sort()

    # {filename: {kdef_name: (kdef_info, kdef_info)}}
    result = {}
    for filename in common_filenames:
        common_kdef_names = list(set(left_kdefs[filename].keys()) 
                                 & set(right_kdefs[filename].keys()))
        left_kdef_names = list(set(left_kdefs[filename].keys()) 
                               - set(right_kdefs[filename].keys()))
        right_kdef_names = list(set(right_kdefs[filename].keys()) 
                                - set(left_kdefs[filename].keys()))
        common_kdef_names.sort()
        left_kdef_names.sort()
        right_kdef_names.sort()

        for item in common_kdef_names:
            left_kdef = left_kdefs[filename][item]
            right_kdef = right_kdefs[filename][item]
            if left_kdef['info'] != right_kdef['info']:
                if filename in result:
                    result[filename][item] = (left_kdef, right_kdef)
                else:
                    result[filename] = {item: (left_kdef, right_kdef)}

        for item in left_kdef_names:
            left_kdef = left_kdefs[filename][item]
            if filename in result:
                result[filename][item] = (left_kdef, None)
            else:
                result[filename] = {item: (left_kdef, None)}

        for item in right_kdef_names:
            right_kdef = right_kdefs[filename][item]
            if filename in result:
                result[filename][item] = (None, right_kdef)
            else:
                result[filename] = {item: (None, right_kdef)}

    for filename in left_filenames:
        for item in left_kdefs[filename].keys():
            left_kdef = left_kdefs[filename][item]
            if filename in result:
                result[filename][item] = (left_kdef, None)
            else:
                result[filename] = {item: (left_kdef, None)}

    for filename in right_filenames:
        for item in right_kdefs[filename].keys():
            right_kdef = right_kdefs[filename][item]
            if filename in result:
                result[filename][item] = (None, right_kdef)
            else:
                result[filename] = {item: (None, right_kdef)}

    # reshape the data to a flat dictionary
    flat_data = {}
    for filename, kdefs_dict in result.items():
        for item, (left_kdef, right_kdef) in kdefs_dict.items():
            key = (filename, item)
            flat_data[key] = {'parent_kdef': left_kdef, 
                              'commit_kdef': right_kdef}

    sorted_data = {k: flat_data[k] for k in sorted(flat_data)}
    return sorted_data


def create_usage_table(project_config, commit_id1, commit_id2):
    left_usage_xml = os.path.join(project_config.project_xml_dir,
                                  commit_id1 + '_usage.xml')
    right_usage_xml = os.path.join(project_config.project_xml_dir,
                                   commit_id2 + '_usage.xml')

    if not os.path.isfile(left_usage_xml):
        logging.error('[{}][xml_diff] usage.xml file not found for commit {}'
                      .format(project_config.project_name, commit_id1[:7]))
        return None
    if not os.path.isfile(right_usage_xml):
        logging.error('[{}][xml_diff] usage.xml file not found for commit {}'
                      .format(project_config.project_name, commit_id2[:7]))
        return None

    data = get_usage_data(project_config, left_usage_xml, right_usage_xml)
    df = pd.DataFrame.from_dict(data, orient='index')

    colored_df = color_usage(df)
    if not colored_df.empty:
        colored_df['parent_usage'] = colored_df['parent_usage'].apply(
            lambda x: ', '.join(x))
        colored_df['commit_usage'] = colored_df['commit_usage'].apply(
            lambda x: ', '.join(x))
        colored_df = colored_df.reset_index()
        colored_df.columns = ['File', 'Kconfig', 'Parent Commit', 'Commit']
    table = colored_df.to_html(None, escape=False, bold_rows=False, 
                               index=False)
    return table


def get_usage_data(project_config, left_usage_xml, right_usage_xml):
    # {filename: {kdef: [lines]}}
    left_usage = parse_usage_xml(project_config, left_usage_xml)
    right_usage = parse_usage_xml(project_config, right_usage_xml)

    common_filenames = list(set(left_usage.keys()) & set(right_usage.keys()))
    left_filenames = list(set(left_usage.keys()) - set(right_usage.keys()))
    right_filenames = list(set(right_usage.keys()) - set(left_usage.keys()))
    common_filenames.sort()
    left_filenames.sort()
    right_filenames.sort()

    # {filename: {kdef: ([parent_usage], [commit_usage])}}
    result = {}
    for filename in common_filenames:
        common_kdefs = list(set(left_usage[filename].keys()) 
                            & set(right_usage[filename].keys()))
        left_kdefs = list(set(left_usage[filename].keys()) 
                          - set(right_usage[filename].keys()))
        right_kdefs = list(set(right_usage[filename].keys()) 
                           - set(left_usage[filename].keys()))
        common_kdefs.sort()
        left_kdefs.sort()
        right_kdefs.sort()

        for kdef in common_kdefs:
            left_lines = left_usage[filename][kdef]
            right_lines = right_usage[filename][kdef]
            if left_lines != right_lines:
                if filename in result:
                    result[filename][kdef] = (left_lines, right_lines)
                else:
                    result[filename] = {kdef: (left_lines, right_lines)}

        for kdef in left_kdefs:
            left_lines = left_usage[filename][kdef]
            if filename in result:
                result[filename][kdef] = (left_lines, [])
            else:
                result[filename] = {kdef: (left_lines, [])}

        for kdef in right_kdefs:
            right_lines = right_usage[filename][kdef]
            if filename in result:
                result[filename][kdef] = ([], right_lines)
            else:
                result[filename] = {kdef: ([], right_lines)}

    for filename in left_filenames:
        for kdef in left_usage[filename].keys():
            left_lines = left_usage[filename][kdef]
            if filename in result:
                result[filename][kdef] = (left_lines, [])
            else:
                result[filename] = {kdef: (left_lines, [])}

    for filename in right_filenames:
        for kdef in right_usage[filename].keys():
            right_lines = right_usage[filename][kdef]
            if filename in result:
                result[filename][kdef] = ([], right_lines)
            else:
                result[filename] = {kdef: ([], right_lines)}

    # reshape the data to a flat dictionary
    flat_data = {}
    for filename, kdefs_dict in result.items():
        for kdef, (old_lines, new_lines) in kdefs_dict.items():
            key = (filename, kdef)
            flat_data[key] = {'parent_usage': old_lines, 
                              'commit_usage': new_lines}

    sorted_data = {k: flat_data[k] for k in sorted(flat_data)}
    return sorted_data


def parse_usage_xml(project_config, xml_file: str):
    tree = ET.parse(xml_file)
    node_KconfigRoot = tree.getroot()
    # {filename: {kdef: [lines]}}
    data = {}
    for node_file in node_KconfigRoot:
        filename = node_file.attrib['fileName']
        for node_Kconfig in node_file:
            kdef = node_Kconfig.attrib['name']
            for prefix in project_config.macro_prefixes:
                if kdef.startswith(prefix):
                    kdef = kdef[len(prefix) : ]
                    break
            for suffix in project_config.macro_suffixes:
                if kdef.endswith(suffix):
                    kdef = kdef[ : len(kdef)-len(suffix)]
                    break
            lines = node_Kconfig.iter('line')
            lines = [item.text for item in lines]
            if filename in data:
                data[filename][kdef] = lines
            else:
                data[filename] = {kdef: lines}
    return data


def color_usage(df):
    for _, row in df.iterrows():
        if len(row['parent_usage']) == 0:
            row['commit_usage'] = [add_class('insert', x) for x in 
                                   row['commit_usage']]
        elif len(row['commit_usage']) == 0:
            row['parent_usage'] = [add_class('delete', x) for x in 
                                   row['parent_usage']]
        else:
            if len(row['parent_usage']) > 1:
                lines = []
                for line in row['parent_usage']:
                    if line in row['commit_usage']:
                        lines.append(line)
                    else:
                        lines.append(add_class('replace', line))
                row['parent_usage'] = lines
            else:
                if row['parent_usage'][0] not in row['commit_usage']:
                    row['parent_usage'] = [add_class('replace', 
                                                     row['parent_usage'][0])]

            if len(row['commit_usage']) > 1:
                lines = []
                for line in row['commit_usage']:
                    if line in row['parent_usage']:
                        lines.append(line)
                    else:
                        lines.append(add_class('replace', line))
                row['commit_usage'] = lines
            else:
                if row['commit_usage'][0] not in row['parent_usage']:
                    row['commit_usage'] = [add_class('replace', 
                                                     row['commit_usage'][0])]
    return df
